 spring:
  datasource:
    url: ${DATABASE_URL} # Ex: jdbc:postgresql://ep-divine-cloud-1234.eu-central-1.aws.neon.tech/troupeau
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # La création des tables est strictement réservée à Flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET} # Clé cryptographique longue
      expiration: 86400000 # 24 heures en millisecondes
  cors:
    allowed-origins: ${FRONTEND_URL} # Ex: https://letroupeau.vercel.app
